name: Latest blog post workflow
on:
    push:
        branches:
            - 'main'
    schedule: # Run workflow automatically
        - cron: '0 */4 * * *'
    workflow_dispatch:
permissions:
    contents: write 

jobs:
    update-readme-with-blog:
        name: Update this repo's README
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: add 2ad.com posts
              uses: gautamkrishnar/blog-post-workflow@v1
              with:
                  feed_list: 'https://2ad.com/feeds/all.atom.xml'
                  comment_tag_name: 'BLOG-POST-LIST'
                  max_post_count: 5
            - name: add YouTube posts
              uses: gautamkrishnar/blog-post-workflow@v1
              with:
                  feed_list: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCThxF_LZZ2gNnzgHSKnaL-A'
                  comment_tag_name: 'VIDEO-LIST'
                  max_post_count: 5
